version: '3'

# https://qiita.com/umeneri/items/6fb3f7560f4a878f6dfd
# https://www.scriptlife.jp/contents/programming/2018/10/21/aws-docker-dynamodb-local/
# services:
#   dynamodblocal:
#     image: amazon/dynamodb-local
#     networks:
#       - default
 
#   dynamodbadmin:
#     image: instructure/dynamo-local-admin
#     networks:
#       - default
#     ports:
#       - 8001:8001
#     environment:
#       DYNAMO_ENDPOINT: http://dynamodblocal:8000/


services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4569:4569"
      - "4572:4572"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
